## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/b2b_mysql_test?characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: sa
    password: select111***
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
## Mybatis 配置
mybatis:
  type-aliases-package: com.usoft.b2b.manage.domain
  mapper-locations: classpath:mapper/*.xml
#  打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8099
logging:
  level:
    com.baomidou.mybatisplus.samples.pagination: debug


